version: '3'

services:
  postgres-db:
    image: postgres
    hostname: postgres-db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD: pypi-server
      POSTGRES_USER: pypi-server
      POSTGRES_DB: pypi-server
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data:
    external: true

networks:
  backend_network:
    external: true