version: '3'

services:
  pypi_server:
    image: mosquito/pypi-server:latest
    hostname: pypi_server
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 8181:80
    networks:
      - backend_network
    volumes:
      - pypi_data:/usr/lib/pypi-server
    environment:
      # Database URL. Use `sqlite3:///` or `mysql://` when needed
      DB: "postgres://pypi-server:pypi-server@postgres-db/pypi-server"

      ## By default random
      #SECRET: changeme

      ## Override standard port
      #PORT: 80

      ## Set "X-Headers" (e.g. X-Forwarded-For)
      #PROXY_MODE: 1

      ## Set 0 when you want to disable proxying from global pypi
      #PYPI_PROXY: 1

      ## Tread-pool size (default cpu_count * 2)
      #POOL_SIZE: 4

      ## Maximum proxy clients count
      #MAX_CLIENTS: 25

      ## PYPI server url
      #PYPY_SERVER: https://pypi.python.org

volumes:
  pypi_data:
    external: true

networks:
  backend_network:
    external: true