version: '3'

services:
  pypiserver:
    image: pypiserver/pypiserver:latest
    hostname: pypiserver
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 8181:8080
    volumes:
      - pypi_packages:/data/packages
    command: --passwords . --authenticate . --overwrite --root /data/packages

volumes:
  pypi_packages:
    external: true